name: Auto Format

on:
  workflow_run:
    workflows:
      - 'Static Checks'
    types:
      - completed

permissions:
  contents: write

jobs:
  auto-format:
    name: 'Auto Format'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Toolkit
        uses: Scony/godot-gdscript-toolkit@master

      - name: Format
        run: gdformat ./

      - name: Commit
        run: |
          git config --global user.name 'Коплик Дмитрий'
          git config --global user.email 'Dkoplik@users.noreply.github.com'
          git commit -am "Автоматическое форматирование кода"
          git push
