name: Static checks

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.gd'
  pull_request:

jobs:
  static-checks:
    name: 'Static checks'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: Scony/godot-gdscript-toolkit@master
    
    - name: Formater
      run: gdformat --check .
      
    - name: Linter
      run: gdlint .
